### ISSUE TITLE
Please improve readme document

### ISSUE THREAD

**Issue by narendranss** [SubhadityaMukherjee/invisiblityCloak#1]
Please add more details in readme document for others to understand the program and run and achieve same kind of invisibility as presented in the video

**Comment by turagabhupathi** [comment]
just paste the code pycharm or related applications and install opencv-python

**Comment by SubhadityaMukherjee** [comment]
This was just a personal project. 
I will update README in a bit. @narendranss @turagabhupathi 
Will add a proper requirements etc.

**Comment by narendranss** [comment]
You project is good. Keep up the good work. A small suggestion, adding sample screen shot samples post adjustment of values will help many.

**Comment by SubhadityaMukherjee** [comment]
@narendranss Hey, Thank you :)
I will add it when im free. It would be different values for everybody so I thought uploading it would just confuse people.
