### ISSUE TITLE
OpenCV: out device of bound (0-0): 1

### ISSUE THREAD

**Issue by direwolf424** [SubhadityaMukherjee/invisiblityCloak#3]
When i am trying to run this command which is given in the readme
`python range_det.py -f HSV --webcam`

I am getting the following error
`OpenCV: out device of bound (0-0): 1
OpenCV: camera failed to properly initialize!`

OS Used:
macOS

version:
opencv-python==4.1.0.25
Python 3.6.5

Any help would be really appreciated @SubhadityaMukherjee

**Comment by SubhadityaMukherjee** [comment]
Change cv2.VideoCapture(1) to cv2.VideoCapture(0). It is a MacOS bug for Coaca applications

**Comment by g4rkk** [comment]
Thank you!!Work for me!
